version: 2

references:
  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  load_code: &load_code
    run:
      name: load code from workspace
      command: |
        mv /tmp/workspace/bigcode-tools/* /tmp/workspace/bigcode-tools/.[!.]* .

jobs:
  fetch_project:
    docker:
      - image: circleci/node:6

    working_directory: ~/bigcode-tools

    steps:
      - checkout
      - run:
          command: |
            mkdir -p /tmp/workspace/bigcode-tools
            mv * .[!.]* /tmp/workspace/bigcode-tools/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - bigcode-tools

  test_nodejs_ast:
    docker:
      - image: circleci/node:6
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - run: cd ast-generators/javascript && yarn
      - run: cd ast-generators/javascript && yarn test

  test_java_ast:
    docker:
      - image: java:8-jdk
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - run: cd ast-generators/java && ./gradlew assemble
      - run: cd ast-generators/java && ./gradlew test

  test_ast_tools:
    docker:
      - image: tuvistavie/sbt:1.0
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - run: sbt test:compile
      - run: sbt test:test

  test_python_ast:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/bigcode-tools
    steps:
      - *attach_workspace
      - *load_code
      - run: sudo apt install python-dev
      - run: cd ast-generators/python && pip install --user -r requirements.txt
      - run: cd ast-generators/python && python -m tox

workflows:
  version: 2
  test_all:
    jobs:
      - fetch_project
      - test_ast_tools:
          requires:
            - fetch_project
      - test_nodejs_ast:
          requires:
            - fetch_project
      - test_python_ast:
          requires:
            - fetch_project
      - test_java_ast:
          requires:
            - fetch_project
